### PR TITLE
Update parent selector

### PR DESCRIPTION
**Pull request by bgitt**

### CODE REVIEW

**Comment by apellerano-pw** [comment]
@kevinwuhoo Any chance we could get a new release with this change? The github DOM has changed and the extension is broken.

**Comment by kevinwuhoo** [comment]
Thanks for the support y'all!

**Comment by kevinwuhoo** [comment]
Ok, just submitted an updated version with this fix to the Chrome Web Store. Needs to undergo review before it gets published. Will let you know when it happens!

**Comment by apellerano-pw** [comment]
thanks everyone!

**Pull request merged**
